version: '3'
services:
  frontend:
    build:
      context: ./client
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./server
    ports:
      - '3001:3001'
    env_file:
      - .env
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
