version: '3.8'
services:
  frontend:
    build:
      context: ./client
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=test

  backend:
    build:
      context: ./server
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=test
      - MONGO_URL=mongodb://mongo:27017/test_db
      - PORT=3001
      - JWT_SECRET=sometestsecret
    stdin_open: true
    tty: true

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
